sudo: false
language: generic

before_install:
  - rvm install 2.2.6
  - gem install dropbox-deployment

script:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create --yes -n paper
  - source activate paper
  - conda install -c conda-forge -c pkgw-forge tectonic
  - vim -N -u NONE -s main-compat.keys main.tex
  - printf "[[default_bundles]]\nurl = \"https://dl.bintray.com/pkgw/tectonic/tl2016extras/2016.0r4/tlextras-2016.0r4.tar\"" | install -D /dev/stdin ~/.config/Tectonic/config.toml
  - tectonic main.tex --print

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then dropbox-deployment; fi
